# Generated by Django 3.2.7 on 2022-05-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendmailmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Enter your names')),
                ('email', models.EmailField(max_length=100, verbose_name='Enter your email')),
            ],
        ),
    ]
